name: Nguyen Nhat Minh
title: Embedded Intern

contact:
  phone: "0365252602"
  email: "nhatminhd27th@gmail.com"
  address [Địa chỉ] x: "K68/5, Ho Ba On, Lien Chieu, Danang"

about_me: |
  I am a fourth-year student studying engineering in the Faculty of Electronics and Telecommunications at Danang University of Science and Technology, actively seeking opportunities for growth and advancement.

education:
  - degree: "Electronics and Telecommunications"
    period: "2020 - Now"
    institution: "Danang University of Technology and Science"
    gpa: "3.47/4"
    details: |
      - Learn about programming, computer hardware, MCU, sensor, freeRTOS, IoT application, computer communication & networking, signals and systems, signals processing, electronics, semiconductors, telecommunication.

achievements_and_certificates:
  - title: "Third Prize awarded in Student Scientific Research at the Faculty of Electronics and Telecommunications in Danang, December 2023."
    link: "https://bit.ly/3rd_prize_award"
  - title: "NVIDIA certificate for completing the Fundamentals of Deep Learning Workshop. (11/2023)"
    link: "https://bit.ly/NVIDIA_Certificate"

technical_skills:
  - category: "MCU"
    skills:
      - "Stm32"
      - "Esp32"
  - category: "Programming language"
    skills:
      - "C/C++"
  - category: "Tools"
    skills:
      - "STM32CubeIDE"
      - "Arduino IDE"
      - "Matlab"
      - "Proteus"
      - "..."

language:
  - name: "English"
    proficiency: "Capable of reading English documents, basic English communication, and writing."