# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Nguyen Nhat Minh
title: Embedded Student
email: nhatminhd27th@gmail.com
website: https://github.com/nhatminhd27th

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: facespics
github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: jameswgrant
linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
   I am a fourth-year student studying engineering in the Faculty of Electronics and Telecommunications at Danang University of Science and Technology, actively seeking opportunities for growth and advancement.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Smart home
        description: | # this will include new lines to allow paragraphs
          Developing a smart home model applying IoTs using freeRTOS, implementing functions such as reading data from the DHT11 temperature sensor, MQ2 gas sensor, and rain sensor, controlling the skylight, turning lights on and off, sending data to the Thingsboard server, and controlling devices online.
      - layout: top-middle
        title: Local weather condition forecast device
        description: | # this will include new lines to allow paragraphs
          Creating a device that can measure water level, temperature, humidity, and altitude in relation to sea level, with the incorporation of the Zambretti algorithm for forecasting local weather conditions.
      
      - layout: top-middle
        title: Single-input audio amplifier
        description: | # this will include new lines to allow paragraphs
          Creating a single-input audio amplifier circuit without an output transformer (OTL) using BJTs, incorporating bass-treble control.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Danang University of Technology and Science
        caption: 2020 - Now
        sub_title: Electronics and Telecommunications
        description: | # this will include new lines to allow paragraphs
          - GPA: 3.52/4

          - Learn about programming, computer hardware, MCU, sensor, freeRTOS, IoT application, computer communication & networking, signals and systems, signals processing, electronics, semiconductors, telecommunication.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
